// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/refresh-token": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Generate new access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh JWT token",
                "parameters": [
                    {
                        "description": "Refresh token request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.RefreshTokenResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/sign-in": {
            "post": {
                "description": "Authenticate user with email and password, returns JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in user",
                "parameters": [
                    {
                        "description": "Sign in request with user credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sign in successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.SignInResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "401": {
                        "description": "Invalid email or password",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "423": {
                        "description": "Your account has been locked",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/sign-in-guest": {
            "post": {
                "description": "Authenticate guest user without credentials, returns limited access tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in guest",
                "parameters": [
                    {
                        "description": "Guest sign in request with optional user agent",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignInGuestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Guest sign in successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/auth.SignInGuestResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "403": {
                        "description": "Guest sign in disabled",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "429": {
                        "description": "Guest session limit reached",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/sign-out": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Revoke user session and invalidate JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign out user",
                "responses": {
                    "200": {
                        "description": "Sign out successfully",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/sign-up": {
            "post": {
                "description": "Register a new user account with email, password, and profile information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Sign up new user",
                "parameters": [
                    {
                        "description": "Sign up request with user details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignUpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "409": {
                        "description": "Email already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trainings": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated list of trainings with optional search and sorting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Get trainings with pagination",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name.asc",
                            "name.desc",
                            "level.asc",
                            "level.desc",
                            "created_at.asc",
                            "created_at.desc"
                        ],
                        "type": "string",
                        "default": "created_at.desc",
                        "description": "Sort field and direction",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term for training name and description",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Trainings retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessPagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/training.TrainingItemResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Training not found",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.SuccessPagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/training.TrainingItemResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create a new training with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Create a new training",
                "parameters": [
                    {
                        "description": "Training creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/training.TrainingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Training created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/training.TrainingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "409": {
                        "description": "Training already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/trainings/sessions/last": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve the most recent training session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Get user's last training session",
                "responses": {
                    "200": {
                        "description": "Last training session retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/training.TrainingSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "No training sessions found",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/trainings/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve detailed training information by training ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Get training by ID",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"8c4a2d27-56e2-4ef3-8a6e-43b812345abc\"",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Training retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/training.TrainingResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Training not found",
                        "schema": {
                            "$ref": "#/definitions/response.Message"
                        }
                    }
                }
            }
        },
        "/trainings/{id}/finish": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Complete an ongoing training session with distance and duration metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Finish a training session",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"8c4a2d27-56e2-4ef3-8a6e-43b812345abc\"",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Training finish session request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/training.TrainingFinishSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Training session finished successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/training.TrainingSessionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "User not found or Training not found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "422": {
                        "description": "Validation errors",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RefreshTokenRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string",
                    "example": "3d3dc788634e05b7d1d5fac06834d3b6a9b62..."
                }
            }
        },
        "auth.RefreshTokenResponse": {
            "type": "object",
            "properties": {
                "expiresInMs": {
                    "type": "integer",
                    "example": 1799999
                },
                "refreshToken": {
                    "type": "string",
                    "example": "3d3dc788634e05b7d1d5fac06834d3b6a9b62..."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "auth.SignInGuestRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "height": {
                    "type": "number",
                    "example": 180
                },
                "weight": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "auth.SignInGuestResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 1799999
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "height": {
                    "type": "number",
                    "example": 180
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "refreshToken": {
                    "type": "string",
                    "example": "3d3dc788634e05b7d1d5fac06834d3b6a9b62..."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "weight": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "auth.SignInRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePassword123"
                }
            }
        },
        "auth.SignInResponse": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "expiresIn": {
                    "type": "integer",
                    "example": 1799999
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "height": {
                    "type": "number",
                    "example": 180
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "refreshToken": {
                    "type": "string",
                    "example": "3d3dc788634e05b7d1d5fac06834d3b6a9b62..."
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "weight": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "auth.SignUpRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "example": 30
                },
                "confirmPassword": {
                    "type": "string",
                    "example": "SecurePassword123"
                },
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "gender": {
                    "type": "string",
                    "example": "male"
                },
                "height": {
                    "type": "number",
                    "example": 180
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePassword123"
                },
                "weight": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "totalPages": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "response.Success": {
            "type": "object",
            "properties": {
                "data": {}
            }
        },
        "response.SuccessPagination": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/response.Pagination"
                }
            }
        },
        "training.TrainingFinishSessionRequest": {
            "type": "object",
            "properties": {
                "distanceMeters": {
                    "type": "integer",
                    "example": 300
                },
                "durationSeconds": {
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "training.TrainingItemResponse": {
            "type": "object",
            "properties": {
                "descriptions": {
                    "type": "string",
                    "example": "Short description about this training"
                },
                "id": {
                    "type": "string",
                    "example": "8c4a2d27-56e2-4ef3-8a6e-43b812345abc"
                },
                "level": {
                    "type": "string",
                    "example": "beginner"
                },
                "name": {
                    "type": "string",
                    "example": "Breaststroke Basics"
                },
                "thumbnailUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/thumbs/breaststroke.png"
                }
            }
        },
        "training.TrainingRequest": {
            "type": "object",
            "properties": {
                "caloriesKcal": {
                    "type": "integer",
                    "example": 120
                },
                "categoryCode": {
                    "type": "string",
                    "example": "BREASTSTROKE"
                },
                "content": {
                    "type": "string",
                    "example": "\u003cp\u003eHTML content here\u003c/p\u003e"
                },
                "descriptions": {
                    "type": "string",
                    "example": "Dasar gaya dada untuk pemula"
                },
                "level": {
                    "type": "string",
                    "example": "beginner"
                },
                "name": {
                    "type": "string",
                    "example": "Breaststroke Basics"
                },
                "thumbnailUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/thumbs/breaststroke.png"
                },
                "time": {
                    "type": "string",
                    "example": "10-15 min"
                },
                "videoUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/videos/breaststroke.mp4"
                }
            }
        },
        "training.TrainingResponse": {
            "type": "object",
            "properties": {
                "caloriesKcal": {
                    "type": "integer",
                    "example": 120
                },
                "categoryCode": {
                    "type": "string",
                    "example": "BREASTSTROKE"
                },
                "categoryName": {
                    "type": "string",
                    "example": "Breaststroke"
                },
                "content": {
                    "type": "string",
                    "example": "\u003cp\u003eHTML content here\u003c/p\u003e"
                },
                "descriptions": {
                    "type": "string",
                    "example": "Short description about this training"
                },
                "id": {
                    "type": "string",
                    "example": "8c4a2d27-56e2-4ef3-8a6e-43b812345abc"
                },
                "level": {
                    "type": "string",
                    "example": "beginner"
                },
                "name": {
                    "type": "string",
                    "example": "Breaststroke Basics"
                },
                "thumbnailUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/thumbs/breaststroke.png"
                },
                "timeLabel": {
                    "type": "string",
                    "example": "10-15 min"
                },
                "videoUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/videos/breaststroke.mp4"
                }
            }
        },
        "training.TrainingSessionResponse": {
            "type": "object",
            "properties": {
                "caloriesKcal": {
                    "type": "integer",
                    "example": 120
                },
                "distanceMeters": {
                    "type": "integer",
                    "example": 1500
                },
                "durationSeconds": {
                    "type": "integer",
                    "example": 1800
                },
                "id": {
                    "type": "string",
                    "example": "8c4a2d27-56e2-4ef3-8a6e-43b812345abc"
                },
                "pace": {
                    "type": "number",
                    "example": 1.2
                },
                "trainingId": {
                    "type": "string",
                    "example": "8c4a2d27-56e2-4ef3-8a6e-43b812345abc"
                },
                "userId": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "Swimo GitHub Repository",
        "url": "https://github.com/rizkyharahap/swimo"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Swimo API",
	Description:      "This is the API documentation for Swimo - a swimming management and tracking application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
